add_newline = false
format = '$docker_context$hostname$username$directory$git_branch$git_commit$git_status[î‚°](fg:blue bg:black) '
palette = 'alex'

[palettes.alex]
black = '#000000'
blue = '#3575a8'
cream = '#fbf1c7'
green = '#487d4a'
grey20 = '#202020'
grey80 = '#808080'
orange = '#d65d0e'
purple = '#b16286'
red = '#cc241d'
white = '#ffffff'
yellow = '#d79921'

[directory]
format = '[ $path](fg:white bg:green)[ $read_only](fg:yellow bg:green)[î‚°](fg:green bg:blue)'
read_only = 'ğŸ”’'
truncate_to_repo = false

[docker_context]
format = '[ ğŸ‹ $context ](fg:orange bg:black)[î‚°](bg:grey20 fg:black)'
only_with_files = false

[git_branch]
format = '[ î‚  $branch](fg:white bg:blue)'

[git_commit]
disabled = false
format = '[ $hash$tag](fg:white bg:blue)'
tag_disabled = false
tag_symbol = ' ğŸ· '

[git_status]
format = '[ ($all_status$ahead_behind )](fg:white bg:blue)'

[hostname]
format = '[ @$hostname ](fg:orange bg:black)[î‚°](bg:grey20 fg:black)'
ssh_only = true

[username]
format = '[ $user ]($style)[î‚°](bg:green fg:grey20)'
show_always = true
style_root = 'fg:red bg:grey20'
style_user = 'fg:cream bg:grey20'
